[versions]
jvm = "17"
agp = "8.2.2"
kotlin = "1.9.21"
nexus-publish = "2.0.0-rc-1"
android-minSdk = "26"
android-compileSdk = "34"
compose = "1.6.0"
compose-plugin = "1.6.0-beta01"

murmurhash = "0.4.0"
cvsparser = "1.10.0"
junit = "4.13.2"
jmh = "1.37"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
murmurhash = { module = "com.goncalossilva:murmurhash", version.ref = "murmurhash" }
cvsparser = { module = "org.apache.commons:commons-csv", version.ref = "cvsparser" }
junit4 = { module = "junit:junit", version.ref = "junit" }
jmh = { module = "org.openjdk.jmh:jmh-core-benchmarks", version.ref = "jmh" }
jmh-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
