# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy to central

env:
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  SIGNING_USER: ${{ secrets.SIGNING_USER }}

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
  deploy:
    needs: build
    environment: Publish
    strategy:
      matrix:
        include:
          # SymSpellKt module publications
          - target: :SymSpellKt:publishIosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKt:publishIosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKt:publishIosSimulatorArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKt:publishMacosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKt:publishMacosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKt:publishAndroidReleasePublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKt:publishJvmPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKt:publishLinuxX64PublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKt:publishMingwX64PublicationToSonatypeRepository
            os: windows-latest
          - target: :SymSpellKt:publishWasmJsPublicationToSonatypeRepository
            os: ubuntu-latest
#          - target: :SymSpellKt:publishWasmWasiPublicationToSonatypeRepository
#            os: ubuntu-latest
          - target: :SymSpellKt:publishJsPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKt:publishKotlinMultiplatformPublicationToSonatypeRepository
            os: ubuntu-latest

          # SymSpellKtFdic module publications
          - target: :SymSpellKtFdic:publishIosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKtFdic:publishIosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKtFdic:publishIosSimulatorArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKtFdic:publishMacosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKtFdic:publishMacosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :SymSpellKtFdic:publishAndroidReleasePublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKtFdic:publishJvmPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKtFdic:publishLinuxX64PublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKtFdic:publishMingwX64PublicationToSonatypeRepository
            os: windows-latest
          - target: :SymSpellKtFdic:publishWasmJsPublicationToSonatypeRepository
            os: ubuntu-latest
#          - target: :SymSpellKtFdic:publishWasmWasiPublicationToSonatypeRepository
#            os: ubuntu-latest
          - target: :SymSpellKtFdic:publishJsPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :SymSpellKtFdic:publishKotlinMultiplatformPublicationToSonatypeRepository
            os: ubuntu-latest

          # Fdic module publications
          - target: :Fdic:publishIosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :Fdic:publishIosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :Fdic:publishIosSimulatorArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :Fdic:publishMacosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :Fdic:publishMacosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :Fdic:publishAndroidReleasePublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :Fdic:publishJvmPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :Fdic:publishLinuxX64PublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :Fdic:publishMingwX64PublicationToSonatypeRepository
            os: windows-latest
          - target: :Fdic:publishWasmJsPublicationToSonatypeRepository
            os: ubuntu-latest
#          - target: :Fdic:publishWasmWasiPublicationToSonatypeRepository
#            os: ubuntu-latest
          - target: :Fdic:publishJsPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :Fdic:publishKotlinMultiplatformPublicationToSonatypeRepository
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.SIGNING_KEY }}
        passphrase: ${{ secrets.SIGNING_PASSWORD }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle publish
      uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
      with:
        arguments: |
          ${{ matrix.target }}
          closeAndReleaseSonatypeStagingRepository
          -Psigning.gnupg.passphrase='${{secrets.SIGNING_PASSWORD}}'
          -PsonatypeUsername='${{secrets.OSSRH_USERNAME}}'
          -PsonatypePassword='${{secrets.OSSRH_PASSWORD}}'
